const fs=require('fs'),vm=require('vm'),assert=require('assert');process.chdir(require('path').resolve(__dirname,'..'));
const allBank=JSON.parse(fs.readFileSync('ascent-app/questions.json','utf8'));let bank=allBank.filter(x=>x.audience==='adult');
class Element{constructor(){this.children=[];this.handlers={};this.textContent='';this.hidden=false;this.disabled=false;this.classList={toggle(){},add(){},remove(){}}}addEventListener(n,f){this.handlers[n]=f}setAttribute(){}append(...e){this.children.push(...e)}replaceChildren(...e){this.children=e}focus(){}}
const storage=new Map();
async function setup(audience="adult"){const els=new Map(),el=id=>{if(!els.has(id))els.set(id,new Element());return els.get(id)};el('audience').value=audience;bank=allBank.filter(x=>x.audience===audience);vm.runInNewContext(fs.readFileSync('ascent-app/game.js','utf8'),{document:{getElementById:el,createElement:()=>new Element()},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},fetch:async()=>({ok:true,json:async()=>allBank}),Math,Set,JSON,Array,Number});await new Promise(r=>setImmediate(r));return {el,click:id=>el(id).handlers.click(),pick:correct=>{const q=bank.find(x=>x.text===el('question').textContent);const b=el('answers').children.find(x=>!x.disabled&&(x.children[1].textContent===q.answers[q.correct])===correct);assert(b);b.handlers.click();},step:correct=>{const q=bank.find(x=>x.text===el('question').textContent);const b=el('answers').children.find(x=>!x.disabled&&(x.children[1].textContent===q.answers[q.correct])===correct);assert(b);b.handlers.click();el('lock').handlers.click();el('next').handlers.click();}}}
(async()=>{
 let g=await setup();assert(!g.el('start').disabled);g.click('start');
 g.click('narrow');assert.equal(g.el('answers').children.filter(x=>!x.disabled).length,2);assert(g.el('narrow').disabled);
 g.click('clue');assert(g.el('hint').textContent.length>0);g.click('chance');g.pick(false);g.click('lock');assert(g.el('feedback').hidden);assert(g.el('chance').disabled);g.step(true);
 g=await setup();assert(!g.el('resume').hidden);g.click('resume');assert(g.el('level').textContent.includes('2/15'));assert(g.el('narrow').disabled);
 for(let i=1;i<15;i++)g.step(true);
 assert(!g.el('result').hidden);assert(g.el('result-score').textContent.includes('Summit Mind'));assert.equal(JSON.parse(storage.get('youtopia-ascent-best-v1')),15);assert(!storage.has('youtopia-ascent-run-v2'));
 g.click('restart');for(let i=0;i<8;i++)g.step(true);g.step(false);assert(g.el('result-score').textContent.includes('6/15'));assert.equal(JSON.parse(storage.get('youtopia-ascent-best-v1')),15);
 g.click('home');g.click('practice');for(let i=0;i<30;i++)g.step(false);assert(g.el('result-score').textContent.includes('0 correct'));assert.equal(g.el('review-list').children.length,30);assert.equal(JSON.parse(storage.get('youtopia-ascent-best-v1')),15);
 g.click('restart');assert(g.el('level').textContent.includes('PRACTICE'));assert(g.el('level').textContent.includes('1/30'));g.click('bank');g.click('home');g.click('start');g.step(true);g.click('bank');assert(g.el('result-score').textContent.includes('1/15'));
 storage.set('youtopia-ascent-run-v2',JSON.stringify({version:2,ids:['unknown']}));g=await setup();assert(g.el('resume').hidden);
 for(const mode of ['kids','teen']){g=await setup(mode);g.click('start');for(let i=0;i<15;i++)g.step(mode==='teen');assert(!g.el('result').hidden);assert(!storage.has('youtopia-ascent-run-v2-'+mode));assert.equal(JSON.parse(storage.get('youtopia-ascent-best-v1')),15);g.click('home');g.click('practice');for(let i=0;i<30;i++)g.step(false);assert.equal(g.el('review-list').children.length,30);g.click('home');g.click('start');g.step(true);g=await setup(mode);assert(!g.el('resume').hidden);g.click('resume');assert(g.el('level').textContent.includes('2/15'));}
 console.log('PASS: Kids and Teen banks, gentle Kids completion, separate progress, youth practice and resume;  full summit; checkpoint loss; banking; practice all 30; lifelines; second chance; resume; corrupt-save handling');
})().catch(e=>{console.error(e);process.exit(1)});
