(() => {
 'use strict';const $=id=>document.getElementById(id),symbols=['☀','☾','✦','◆','♧','△','◎','≈'];
 let deck=[],open=[],matched=new Set(),turns=0,timer=null;
 function renderDeck(){ $('moves').textContent=turns+' turns';$('pairs').textContent=matched.size/2+' / 8 pairs';$('deck').replaceChildren(...deck.map((symbol,n)=>{const b=document.createElement('button');b.className='memory-card'+(matched.has(n)?' matched':'');b.textContent=open.includes(n)||matched.has(n)?symbol:'◇';b.setAttribute('aria-label',matched.has(n)?'Matched '+symbol:open.includes(n)?'Card '+(n+1)+': '+symbol:'Hidden card '+(n+1));b.disabled=matched.has(n);b.addEventListener('click',()=>flip(n));return b})); }
 function flip(n){if(open.length===2||open.includes(n)||matched.has(n))return;open.push(n);if(open.length===2){turns++;if(deck[open[0]]===deck[open[1]]){open.forEach(x=>matched.add(x));open=[];$('memory-status').textContent=matched.size===16?'All eight pairs found in '+turns+' turns. Well played.':'A match. Keep exploring.';}else{$('memory-status').textContent='Two different symbols. Try another pair.';timer=setTimeout(()=>{open=[];renderDeck();},950);}}renderDeck();if(open.length<2){const available=[...$('deck').children].find(x=>!x.disabled);available?.focus();}}
 function reset(){clearTimeout(timer);deck=[...symbols,...symbols];for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}open=[];matched=new Set();turns=0;$('memory-status').textContent='Choose your first card.';renderDeck()}
 let elapsed=0,startTime=0,active=false,frame=0,lastPhase='';
 function stop(){if(active){elapsed=Math.min(60000,elapsed+performance.now()-startTime);active=false}cancelAnimationFrame(frame);$('pause-calm').disabled=true;$('start-calm').disabled=false;$('start-calm').textContent=elapsed>0&&elapsed<60000?'Continue':'Begin one minute';}
 function tick(now){if(!active)return;const total=elapsed+now-startTime;if(total>=60000){elapsed=60000;active=false;$('pause-calm').disabled=true;$('start-calm').disabled=false;$('start-calm').textContent='Begin again';$('breath-label').textContent='A moment, complete.';$('calm-status').textContent='One quiet minute complete.';$('orb').style.transform='scale(1)';return}const pos=(total%10000)/1000,phase=pos<4?'Breathe in gently':'Breathe out gently';$('orb').style.transform='scale('+(pos<4?1+pos/8:1.5-(pos-4)/12)+')';$('breath-label').textContent=phase;if(lastPhase!==phase){$('calm-status').textContent=phase+'. '+Math.ceil((60000-total)/1000)+' seconds remaining.';lastPhase=phase;}frame=requestAnimationFrame(tick);}
 $('start-calm').addEventListener('click',()=>{if(elapsed>=60000)elapsed=0;active=true;startTime=performance.now();lastPhase='';$('start-calm').disabled=true;$('pause-calm').disabled=false;frame=requestAnimationFrame(tick)});
 $('pause-calm').addEventListener('click',()=>{stop();$('breath-label').textContent='Paused';$('calm-status').textContent='Continue when you are ready.'});
 $('reset-calm').addEventListener('click',()=>{stop();elapsed=0;$('orb').style.transform='scale(1)';$('breath-label').textContent='Ready when you are.';$('calm-status').textContent='One minute. No score. Just a pause.';$('start-calm').textContent='Begin one minute'});
 $('reset-memory').addEventListener('click',reset);
 function route(){stop();const calm=location.hash==='#calm';$('calm').hidden=!calm;$('memory').hidden=calm;}
 window.addEventListener('hashchange',route);document.addEventListener('visibilitychange',()=>{if(document.hidden&&active){stop();$('breath-label').textContent='Paused';$('calm-status').textContent='Paused while the app is in the background.'}});reset();route();
})();
