(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),key='youtopia-vital-rush-v1',colours={mint:'#81f4c0',gold:'#ffdf7c',violet:'#c5a2ff'},foods=['🥑','🍎','🥕','🥚','🫘'];
let saved={best:{},foodTotal:0,suit:'mint',preferences:{}},storageOK=true;try{const raw=JSON.parse(localStorage.getItem(key));if(raw&&typeof raw==='object'){saved.best={};if(raw.best&&typeof raw.best==='object')for(const [k,v] of Object.entries(raw.best)){if(/^(normal|daily)-(gentle|regular)(-\d{4}-\d{1,2}-\d{1,2})?$/.test(k)&&Number.isSafeInteger(v)&&v>=0)saved.best[k]=v;}saved.preferences=raw.preferences&&typeof raw.preferences==='object'?raw.preferences:{};saved.foodTotal=Number.isSafeInteger(raw.foodTotal)&&raw.foodTotal>=0?raw.foodTotal:0;saved.suit=Object.prototype.hasOwnProperty.call(colours,raw.suit)?raw.suit:'mint';}}catch{storageOK=false;}
if((saved.suit==='gold'&&saved.foodTotal<30)||(saved.suit==='violet'&&saved.foodTotal<80))saved.suit='mint';
let run=null,w=1,h=1,last=0,ambient=0,mode='normal',bestKey='',toastUntil=0,sound=false,audio=null,shake=0,newBest=false,pointer=null;
$('motion').checked=saved.preferences.motion===true||matchMedia('(prefers-reduced-motion: reduce)').matches;$('gentle').checked=saved.preferences.gentle===true;
function persist(){try{localStorage.setItem(key,JSON.stringify(saved));}catch{storageOK=false;}}
function announce(msg){$('announcer').textContent=msg;}
function toast(msg){$('toast').textContent=msg;toastUntil=performance.now()+2200;announce(msg);}
function tone(freq=640){if(!sound)return;try{audio||=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.65,audio.currentTime+.12);gain.gain.setValueAtTime(.065,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.17);}catch{sound=false;}}
function dateKey(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;}
function hash(text){let n=2166136261;for(const c of text)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0;}
function best(){const value=saved.best[bestKey];return Number.isFinite(value)&&value>=0?value:0;}
function homeBest(){const pace=$('gentle').checked?'gentle':'regular',score=saved.best['normal-'+pace]||0;$('home-best').textContent=score?`Your ${pace} best: ${score.toLocaleString()} · ${saved.foodTotal} food collected`:saved.foodTotal?`${saved.foodTotal} food collected · Your next level is waiting.`:'Your first run starts here.';}
function home(){run=null;$('home').hidden=false;$('result').hidden=true;$('pause-screen').hidden=true;$('hud').hidden=true;$('controls').hidden=true;$('pause').disabled=true;homeBest();document.querySelectorAll('[data-suit]').forEach(b=>{b.classList.toggle('selected',b.dataset.suit===saved.suit);b.setAttribute('aria-pressed',String(b.dataset.suit===saved.suit));});}
function start(daily=false,practice=false){mode=practice?'practice':daily?'daily':'normal';bestKey=mode+($('gentle').checked?'-gentle':'-regular')+(daily?'-'+dateKey():'');run=new VitalRushCore.Run({seed:daily?hash(dateKey()):Math.floor(Math.random()*4294967296),gentle:practice||$('gentle').checked,practice});newBest=false;shake=0;last=0;for(const id of ['home','result','pause-screen'])$(id).hidden=true;$('hud').hidden=false;$('controls').hidden=false;$('pause').disabled=false;canvas.focus();toast(practice?'Practice · 35 seconds, no lost lives. Try changing lanes.':daily?'Daily route · Same course today':'Collect food. Jump low hurdles. Dodge tall walls.');tone(440);updateHUD();}
function pause(){if(run?.phase!=='running')return;run.pause();$('pause-screen').hidden=false;$('controls').hidden=true;$('resume').focus();announce('Game paused.');}
function resume(){if(run?.phase!=='paused')return;run.resume();last=0;$('pause-screen').hidden=true;$('controls').hidden=false;canvas.focus();}
function finish(){if(!run||!$('result').hidden)return;run.finish();$('toast').textContent='';toastUntil=0;const previous=best();newBest=!run.practice&&run.score>previous;if(!run.practice){saved.best[bestKey]=Math.max(previous,run.score);saved.foodTotal+=run.food;persist();}$('pause-screen').hidden=true;$('hud').hidden=true;$('controls').hidden=true;$('pause').disabled=true;$('result').hidden=false;$('final-score').textContent=run.score.toLocaleString();$('result-label').textContent=run.practice?'PRACTICE COMPLETE':newBest?'NEW PERSONAL BEST':'RUN COMPLETE';$('result-stats').textContent=`${run.food} food collected · ${Math.round(run.time)} seconds · ${run.gentle?'Gentle':'Regular'} pace`;$('result-best').textContent=run.practice?'Practice scores and food do not change your records.':storageOK?`Best on this ${mode==='daily'?'daily route':'pace'}: ${best().toLocaleString()}`:'Browser storage unavailable. Scores last for this visit.';$('mission').textContent=run.food>=20?'Fuel mission complete: 20 food!':`${run.food}/20 food this run. Every pickup counts.`;if(saved.foodTotal>=80)$('mission').textContent+=' Violet suit unlocked.';else if(saved.foodTotal>=30)$('mission').textContent+=' Gold suit unlocked.';$('result-title').focus();announce(`Run complete. Score ${run.score}. ${newBest?'New personal best.':''}`);tone(newBest?880:330);}
function updateHUD(){$('score').textContent=run.score.toLocaleString();$('energy-fill').style.width=(run.surge>0?100:run.energy)+'%';$('energy-label').textContent=run.practice?`PRACTICE · ${Math.max(0,35-Math.floor(run.time))}s`:run.surge>0?`GLOW RUSH · ${Math.ceil(run.surge)}s`:run.shield?'SHIELD READY · FUEL YOUR FLOW':'FUEL YOUR FLOW';$('lives').textContent='♥ '.repeat(run.lives).trim();$('lives').setAttribute('aria-label',`${run.lives} lives`);}
function resize(){const box=canvas.getBoundingClientRect();w=box.width;h=box.height;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);}
function polygon(points,fill){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=fill;ctx.fill();}
function line(x1,y1,x2,y2,colour,width=2){ctx.strokeStyle=colour;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function oval(x,y,rx,ry,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function round(x,y,width,height,r,fill){ctx.fillStyle=fill;ctx.beginPath();r=Math.min(r,width/2,height/2);ctx.moveTo(x+r,y);ctx.arcTo(x+width,y,x+width,y+height,r);ctx.arcTo(x+width,y+height,x,y+height,r);ctx.arcTo(x,y+height,x,y,r);ctx.arcTo(x,y,x+width,y,r);ctx.closePath();ctx.fill();}
function project(lane,z){const d=Math.pow(Math.max(0,1-z),2);return{x:w/2+lane*(w*.27*d+w*.012),y:h*.22+d*(h*.73),scale:.15+d*.85};}
function object(o){const p=project(o.lane,o.z),s=p.scale*Math.min(w/700,1.05);ctx.save();ctx.translate(p.x,p.y);ctx.scale(s,s);if(o.hit)ctx.globalAlpha=.25;oval(0,8,27,8,'#020d1280');if(o.kind==='food'){oval(0,-20,31,31,'#143f40');ctx.font='38px system-ui';ctx.textAlign='center';ctx.fillText(foods[o.food],0,-5);}else if(o.kind==='shield'){polygon([[0,-63],[27,-50],[22,-22],[0,-6],[-22,-22],[-27,-50]],'#9ccfff');line(-10,-35,-1,-26,'#113a4a',4);line(-1,-26,14,-45,'#113a4a',4);}else if(o.kind==='research'){oval(0,-30,28,28,'#216779');for(let i=0;i<4;i++){const y=-49+i*12;line(-12,y,12,y+5,'#b7ecff',3);oval(-12,y,4,4,'#b7ecff');oval(12,y+5,4,4,'#b7ecff');}}else if(o.kind==='wall'){round(-40,-115,80,115,10,'#dc7480');round(-31,-106,62,97,5,'#66384b');line(-25,-90,25,-40,'#f2abb3',9);line(25,-90,-25,-40,'#f2abb3',9);}else{round(-43,-36,86,33,5,'#f7c971');round(-35,-30,18,25,2,'#9e6c42');round(16,-30,18,25,2,'#9e6c42');line(-43,-40,43,-40,'#ffdf96',8);}ctx.restore();}
function runner(){const lane=run?run.visualLane:.65,p=project(lane,.065),s=Math.min(w/620,1.1)*(run?.surge>0?1.32:1),jump=run?Math.sin(run.jump/.8*Math.PI)*90:0,t=run?.phase==='running'?run.time*12:ambient*2,colour=colours[saved.suit];ctx.save();ctx.translate(p.x,p.y);oval(0,9,34*s,9*s,'#030f1680');ctx.translate(0,-jump);ctx.scale(s,s);if(run?.invulnerable>0&&Math.floor(ambient*12)%2)ctx.globalAlpha=.45;if(run?.surge>0){oval(0,-49,58,76,'#9dfad52a');ctx.shadowColor=colour;ctx.shadowBlur=22;}if(run?.shield){ctx.strokeStyle='#a1d8ff';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,-50,53,73,0,0,Math.PI*2);ctx.stroke();}const swing=Math.sin(t)*12;line(-13,-35,-16+swing,0,colour,16);line(13,-35,16-swing,0,colour,16);round(-25,-77,50,50,13,colour);line(-25,-65,-37,-38+swing,colour,12);line(25,-65,37,-38-swing,colour,12);round(-27,-116,54,43,15,colour);round(-20,-109,40,23,9,'#18364a');round(-13,-104,26,5,2,'#b8f5fa');polygon([[19,-76],[50,-68],[24,-59]],'#ffdf7c');round(-12,-67,24,18,4,'#164e4d');line(-6,-58,6,-58,'#e6fff1',3);ctx.restore();}
function draw(){ctx.clearRect(0,0,w,h);ctx.save();if(shake>0&&!$('motion').checked)ctx.translate(Math.sin(ambient*90)*shake,0);const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#092a36');sky.addColorStop(.55,'#123e41');sky.addColorStop(1,'#07171e');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);oval(w*.72,h*.16,Math.min(w*.11,70),Math.min(w*.11,70),'#b8f7d8');polygon([[0,h*.32],[w*.15,h*.14],[w*.34,h*.35],[w*.5,h*.18],[w*.75,h*.37],[w,h*.21],[w,h*.6],[0,h*.6]],'#17494d');polygon([[0,h*.43],[w*.2,h*.3],[w*.45,h*.46],[w*.7,h*.29],[w,h*.44],[w,h],[0,h]],'#123c3b');polygon([[w*.46,h*.22],[w*.54,h*.22],[w*1.03,h],[w*-.03,h]],'#132b35');for(const lane of [-1.5,-.5,.5,1.5]){const far=project(lane,1),near=project(lane,-.03);line(far.x,far.y,near.x,near.y,lane===-1.5||lane===1.5?'#75d8b8':'#436a6b',lane===-1.5||lane===1.5?4:2);}
 const travel=run?run.distance:$('motion').checked?0:ambient*.035;for(let i=0;i<16;i++){const z=1-((i/16+travel*.32)%1),p=project(0,z);line(w/2-w*.43*p.scale,p.y,w/2+w*.43*p.scale,p.y,'#26464e',1);}
 for(let side of [-1,1])for(let i=0;i<7;i++){const z=1-((i/7+travel*.21)%1),p=project(side*2.05,z),s=p.scale;line(p.x,p.y,p.x,p.y-100*s,'#388772',6*s);oval(p.x,p.y-104*s,22*s,38*s,'#5dc79b');oval(p.x+side*18*s,p.y-74*s,16*s,25*s,'#399d86');}
 if(run)run.objects.slice().sort((a,b)=>b.z-a.z).forEach(object);runner();ctx.restore();}
function frame(now){const dt=last?Math.min((now-last)/1000,.05):0;last=now;ambient+=dt;shake=Math.max(0,shake-dt*20);if(run?.phase==='running'){run.tick(dt);for(const event of run.drain()){if(event.kind==='surge')toast('GLOW RUSH! Grow, glow & double your pickup points.');else if(event.kind==='shield')toast('Shield ready. One collision covered.');else if(event.kind==='research')toast(run.surge>0?'Research token +200':'Research token +100');else if(event.kind==='saved')toast('Shield saved you!');else if(event.kind==='practice-hit')toast(event.obstacle==='wall'?'Tall wall: move to another lane.':'Low hurdle: jump just before you reach it.');else if(event.kind==='hit'){shake=10;toast(`${run.lives} ${run.lives===1?'life':'lives'} left. Keep going!`);}if(event.kind==='food')tone(650);else if(event.kind==='hit')tone(180);else tone(880);}updateHUD();if(run.phase==='ended')finish();}if(now>toastUntil)$('toast').textContent='';draw();requestAnimationFrame(frame);}
$('start').onclick=()=>start(false);$('daily').onclick=()=>start(true);$('again').onclick=()=>start(mode==='daily',mode==='practice');$('training').onclick=()=>start(false,true);$('menu').onclick=home;$('pause').onclick=pause;$('resume').onclick=resume;$('quit').onclick=finish;$('left').onclick=()=>run?.move(-1);$('right').onclick=()=>run?.move(1);$('jump').onclick=()=>run?.leap();$('about').onclick=()=>{$('notes').showModal();};$('reset-progress').onclick=()=>{$('confirm-reset').showModal();};$('cancel-reset').onclick=()=>{$('confirm-reset').close();$('reset-progress').focus();};$('do-reset').onclick=()=>{saved={best:{},foodTotal:0,suit:'mint',preferences:{gentle:$('gentle').checked,motion:$('motion').checked}};persist();$('confirm-reset').close();home();toast('Scores and unlocks reset.');};$('close-notes').onclick=()=>{$('notes').close();$('about').focus();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Disable game sound':'Enable game sound');if(sound)tone();};document.querySelectorAll('[data-suit]').forEach(b=>b.onclick=()=>{const suit=b.dataset.suit,need=suit==='gold'?30:suit==='violet'?80:0;if(saved.foodTotal<need){toast(`${need-saved.foodTotal} more food to unlock this suit.`);return;}saved.suit=suit;persist();home();});
for(const id of ['gentle','motion'])$(id).addEventListener('change',()=>{saved.preferences={gentle:$('gentle').checked,motion:$('motion').checked};persist();homeBest();});
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Escape'||e.key.toLowerCase()==='p'){if(run?.phase==='running')pause();else if(run?.phase==='paused')resume();return;}if(run?.phase!=='running')return;if(['ArrowLeft','ArrowRight','ArrowUp',' ','a','d','A','D'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')run.move(-1);else if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')run.move(1);else run.leap();}});
canvas.addEventListener('pointerdown',e=>{if(run?.phase!=='running')return;pointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(Math.abs(dx)>25&&Math.abs(dx)>Math.abs(dy))run?.move(Math.sign(dx));else if(dy< -20||Math.abs(dx)<15&&Math.abs(dy)<15)run?.leap();});canvas.addEventListener('pointercancel',()=>pointer=null);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);document.addEventListener('youtopia-pause',pause);window.addEventListener('resize',pause);new ResizeObserver(resize).observe(canvas);home();resize();requestAnimationFrame(frame);
})();
